export const AREA_SELECTED="AREA_SELECTED";
export const CATEGORY_SELECTED="CATEGORY_SELECTED";
export const SHOP_DATA="SHOP_DATA";
export const SHOP_DATA_ARRAY="SHOP_DATA_ARRAY";
export const SHOP_DATA_ARRAY_DELETE="SHOP_DATA_ARRAY_DELETE";
export const AREA_FILTER = "AREA_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const STATUS_FILTER="STATUS_FILTER";